Repository Message-Photon-Studios/Rock-Bottom, pull requests merged in 2023-04, with the labels that each got.

#91 Basic combat
  Assets/Animations/Player/Player-attack-hand.anim
  Assets/Animations/Player/PlayerController.controller
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/Scripts/EnemyStats.cs.meta
  Assets/InputSystem/Controls.cs
  Assets/InputSystem/Controls.inputactions
  Assets/Player/Player.prefab
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpell.cs
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellImpact.cs
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellSpawn.cs
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Player/SpellsSystem/PlayerDefaultAttack.cs
  Assets/Player/SpellsSystem/PlayerDefaultAttack.cs.meta
  Assets/Player/TestDefaultSpell.prefab
  Assets/Scenes/PlayerColorsCombatTest.unity
Labels: System design

#92 Player movement improvements
  Assets/Animations/Player/PlayerController.controller
  Assets/Animations/Player/PlayerGrapple.anim
  Assets/Animations/Player/PlayerGrapple.anim.meta
  Assets/Player/Player.prefab
  Assets/Player/PlayerMovement.cs
  Assets/Player/PlayerSprite/sylvia_grapple.png
  Assets/Player/PlayerSprite/sylvia_grapple.png.meta
Labels: Gameplay Design, System design, Animation

#108 ColorSlot for UI added
  Assets/Player/ColorSystem/ColorInventory.cs
  Assets/Scenes/UITestScene.unity
  Assets/UI/Canvas.prefab
  Assets/UI/ColorSlotController.cs
  Assets/UI/ColorSlotController.cs.meta
  Assets/UI/PotionHandler.cs
  Assets/UI/frameColorSlots.png
  Assets/UI/frameColorSlots.png.meta
Labels: UI Design

#110 Added sylvias default attack sprite sheets
  Assets/Animations/Player/Player-default-attack.anim
  Assets/Animations/Player/Player-default-attack.anim.meta
  Assets/Animations/Player/sylvia-smack-sheet.png
  Assets/Animations/Player/sylvia-smack-sheet.png.meta
Labels: Graphical design, Animation

#111 Implement crystal sword guy
  Assets/Animations/CrystalSword/Crystal_Sword_Controller.controller
  Assets/Animations/CrystalSword/Crystal_Sword_Controller.controller.meta
  Assets/Animations/CrystalSword/Death-crystal-sword.anim
  Assets/Animations/CrystalSword/Swing-crystal-sword-Sheet_0.controller
  Assets/Animations/CrystalSword/Swing-crystal-sword-Sheet_0.controller.meta
  Assets/Animations/CrystalSword/Swing-crystal-sword.anim
  Assets/Animations/CrystalSword/SwingCrystalSword.anim
  Assets/Animations/CrystalSword/SwingCrystalSword.anim.meta
  Assets/Animations/CrystalSword/crystal-sword-idle-Sheet_0.controller
  Assets/Animations/CrystalSword/crystal-sword-swing-Sheet_0.controller
  Assets/Animations/CrystalSword/crystal-sword-walk-Sheet_0.controller
  Assets/Animations/CrystalSword/death-crystal-sword-Sheet_0.controller
  Assets/Enemies/BehaviourTree.meta
  Assets/Enemies/BehaviourTree/Node.cs
  Assets/Enemies/BehaviourTree/Node.cs.meta
  Assets/Enemies/BehaviourTree/Selector.cs
  Assets/Enemies/BehaviourTree/Selector.cs.meta
  Assets/Enemies/BehaviourTree/Sequence.cs
  Assets/Enemies/BehaviourTree/Sequence.cs.meta
  Assets/Enemies/BehaviourTree/Tree.cs
  Assets/Enemies/BehaviourTree/Tree.cs.meta
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Crystoffer.prefab.meta
  Assets/Enemies/EnemyBehaviours.meta
  Assets/Enemies/EnemyBehaviours/AnimationTrigger.cs
  Assets/Enemies/EnemyBehaviours/AnimationTrigger.cs.meta
  Assets/Enemies/EnemyBehaviours/CheckBool.cs
  Assets/Enemies/EnemyBehaviours/CheckBool.cs.meta
  Assets/Enemies/EnemyBehaviours/CheckPlatformEdge.cs
  Assets/Enemies/EnemyBehaviours/CheckPlatformEdge.cs.meta
  Assets/Enemies/EnemyBehaviours/CheckPlayerArea.cs
  Assets/Enemies/EnemyBehaviours/CheckPlayerArea.cs.meta
  Assets/Enemies/EnemyBehaviours/DamagePlayer.cs
  Assets/Enemies/EnemyBehaviours/DamagePlayer.cs.meta
  Assets/Enemies/EnemyBehaviours/NormalAttack.cs
  Assets/Enemies/EnemyBehaviours/NormalAttack.cs.meta
  Assets/Enemies/EnemyBehaviours/RandomPatroll.cs
  Assets/Enemies/EnemyBehaviours/RandomPatroll.cs.meta
  Assets/Enemies/EnemyBehaviours/SetParentVariable.cs
  Assets/Enemies/EnemyBehaviours/SetParentVariable.cs.meta
  Assets/Enemies/Scripts/CrystalSwordEnemy.cs
  Assets/Enemies/Scripts/CrystalSwordEnemy.cs.meta
  Assets/Enemies/Scripts/Enemy.cs
  Assets/Enemies/Scripts/Enemy.cs.meta
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Player/Main Camera.prefab
  Assets/Player/Player.prefab
  Assets/Player/PlayerMovement.cs
  Assets/Player/PlayerStats.cs
  Assets/Scenes/PlayerColorsCombatTest.unity
  ProjectSettings/TagManager.asset
Labels: Gameplay Design, System design

#102 Player information
  Assets/Player/PlayerStats.cs
Labels: System design

#116 Added Enemy Health for UI and changed the folder structure in UI
  Assets/Scenes/UITestScene.unity
  Assets/UI/EnemyUI.meta
  Assets/UI/EnemyUI/EnemyHp.prefab
  Assets/UI/EnemyUI/EnemyHp.prefab.meta
  Assets/UI/EnemyUI/EnemyHpController.cs
  Assets/UI/EnemyUI/EnemyHpController.cs.meta
  Assets/UI/PlayerUI.meta
  Assets/UI/PlayerUI/ColorSlotController.cs
  Assets/UI/PlayerUI/ColorSlotController.cs.meta
  Assets/UI/PlayerUI/HealthBarBorder.png
  Assets/UI/PlayerUI/HealthBarBorder.png.meta
  Assets/UI/PlayerUI/Heart.png
  Assets/UI/PlayerUI/Heart.png.meta
  Assets/UI/PlayerUI/PlayerHpController.cs
  Assets/UI/PlayerUI/PlayerHpController.cs.meta
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/PlayerUI.prefab.meta
  Assets/UI/PlayerUI/UIController.cs
  Assets/UI/PlayerUI/UIController.cs.meta
  Assets/UI/PlayerUI/frameColorSlots.png
  Assets/UI/PlayerUI/frameColorSlots.png.meta
Labels: UI Design

#127 added rolling animation to pebble-sword
  Assets/Animations/PebbleSword/Roll-pebble-sword.anim
  Assets/Animations/PebbleSword/Roll-pebble-sword.anim.meta
  Assets/Animations/PebbleSword/pebble-sword-roll-Sheet_0.controller
  Assets/Animations/PebbleSword/pebble-sword-roll-Sheet_0.controller.meta
  Assets/Animations/PebbleSword/roll-pebble-sword-Sheet.png
  Assets/Animations/PebbleSword/roll-pebble-sword-Sheet.png.meta
  Assets/Scenes/AnimationTests.unity
Labels: Animation

#129 Fixed the player camera
  Assets/Animations/Player/PlayerController.controller
  Assets/Player/Camera.meta
  Assets/Player/Camera/CameraFocus.cs
  Assets/Player/Camera/CameraFocus.cs.meta
  Assets/Player/Camera/CameraMovement.cs
  Assets/Player/Camera/CameraMovement.cs.meta
  Assets/Player/CameraFocus.prefab
  Assets/Player/CameraFocus.prefab.meta
  Assets/Player/Main Camera.prefab
  Assets/Player/Player.prefab
  Assets/Player/PlayerMovement.cs
  Assets/Scenes/Gem.unity
Labels: Gameplay Design, System design

#128 Bug fixes
  Assets/Enemies/Scripts/Enemy.cs
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Player/ColorSystem/GameColor/Blue.asset
  Assets/Player/ColorSystem/GameColor/Brown.asset
  Assets/Player/ColorSystem/GameColor/Green.asset
  Assets/Player/ColorSystem/GameColor/Orange.asset
  Assets/Player/ColorSystem/GameColor/Purple.asset
  Assets/Player/ColorSystem/GameColor/Red.asset
  Assets/Player/ColorSystem/GameColor/Yellow.asset
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Scenes/Gem.unity
  Assets/TechArt/Shaders/Masks/Swing-crystal-sword-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/Swing-pebble-sword-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/crystal-sword-idle-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/crystal-sword-walk-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/death-crystal-sword-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/death-pebble-sword-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/pebble-sword-idle-Sheet_mask.png.meta
  Assets/TechArt/Shaders/Masks/pebble-sword-walk-Sheet_mask.png.meta
Labels: System design

#132 [Add] the finalized the 'brown' particle
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/TechArt/Particles/color/BrownParticles.prefab
Labels: Graphical design, Tech Art

#130 Added death animation without fadeout as sleep animation
  Assets/Animations/CrystalSword/Sleep-crystal-sword.anim
  Assets/Animations/CrystalSword/Sleep-crystal-sword.anim.meta
  Assets/Animations/CrystalSword/sleep-crystal-sword-Sheet.png
  Assets/Animations/CrystalSword/sleep-crystal-sword-Sheet.png.meta
  Assets/Animations/CrystalSword/sleep-crystal-sword-Sheet_0 (1).controller
  Assets/Animations/CrystalSword/sleep-crystal-sword-Sheet_0 (1).controller.meta
  Assets/Animations/PebbleSword/Sleep-pebble-sword.anim
  Assets/Animations/PebbleSword/Sleep-pebble-sword.anim.meta
  Assets/Animations/PebbleSword/sleep-pebble-sword-Sheet.png
  Assets/Animations/PebbleSword/sleep-pebble-sword-Sheet.png.meta
  Assets/Animations/PebbleSword/sleep-pebble-sword-Sheet_0.controller
  Assets/Animations/PebbleSword/sleep-pebble-sword-Sheet_0.controller.meta
  Assets/Scenes/AnimationTests.unity
Labels: Animation

#145 Color slot UI update
  Assets/UI/PlayerUI/Bottle.png
  Assets/UI/PlayerUI/Bottle.png.meta
  Assets/UI/PlayerUI/ColorSlotController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
Labels: UI Design

#154 added new frame to players Healthbar
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/healthbarFrame-mask.png
  Assets/UI/PlayerUI/healthbarFrame-mask.png.meta
  Assets/UI/PlayerUI/healthbarFrame.png
  Assets/UI/PlayerUI/healthbarFrame.png.meta
Labels: UI Design

#146 added healthbar to crystoffer
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Scenes/UITestScene.unity
  Assets/UI/EnemyUI/EnemyHp.prefab
  Assets/UI/EnemyUI/EnemyHpController.cs
Labels: UI Design

#156 Implemented Big Cryss
  Assets/Animations/Big Cryss.meta
  Assets/Animations/Big Cryss/BigCryssAnimator.controller
  Assets/Animations/Big Cryss/BigCryssAnimator.controller.meta
  Assets/Animations/Big Cryss/Big_Cryss_Attack.anim
  Assets/Animations/Big Cryss/Big_Cryss_Attack.anim.meta
  Assets/Animations/Big Cryss/Big_Cryss_Dead.anim
  Assets/Animations/Big Cryss/Big_Cryss_Dead.anim.meta
  Assets/Animations/Big Cryss/Big_Cryss_Idle.anim
  Assets/Animations/Big Cryss/Big_Cryss_Idle.anim.meta
  Assets/Animations/Big Cryss/Big_Cryss_Walk.anim
  Assets/Animations/Big Cryss/Big_Cryss_Walk.anim.meta
  Assets/Animations/Big Cryss/big_cryss_attack.png
  Assets/Animations/Big Cryss/big_cryss_attack.png.meta
  Assets/Animations/Big Cryss/big_cryss_ded.png
  Assets/Animations/Big Cryss/big_cryss_ded.png.meta
  Assets/Animations/Big Cryss/big_cryss_idle.png
  Assets/Animations/Big Cryss/big_cryss_idle.png.meta
  Assets/Animations/Big Cryss/big_cryss_walk.png
  Assets/Animations/Big Cryss/big_cryss_walk.png.meta
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Big Cryss.prefab.meta
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/EnemyBehaviours/CheckPlatformEdgePartly.cs
  Assets/Enemies/EnemyBehaviours/CheckPlatformEdgePartly.cs.meta
  Assets/Enemies/EnemyBehaviours/PlatformChase.cs
  Assets/Enemies/EnemyBehaviours/PlatformChase.cs.meta
  Assets/Enemies/EnemyBehaviours/RandomPatroll.cs
  Assets/Enemies/Scripts/BigCryss.cs
  Assets/Enemies/Scripts/BigCryss.cs.meta
  Assets/Scenes/PlayerColorsCombatTest.unity
Labels: Gameplay Design, System design

#152 Reworked the colorSlot system in UI
  Assets/Scenes/UITestScene.unity
  Assets/UI/PlayerUI/ColorSlotController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/UIController.cs
Labels: UI Design

#159 Added editor lock plugin
  Assets/EasyShortcutLockInspector-main.meta
  Assets/EasyShortcutLockInspector-main/.gitattributes
  Assets/EasyShortcutLockInspector-main/.gitignore
  Assets/EasyShortcutLockInspector-main/Editor.meta
  Assets/EasyShortcutLockInspector-main/Editor/EasyShortCutLockInspector.Editor.asmdef
  Assets/EasyShortcutLockInspector-main/Editor/EasyShortCutLockInspector.Editor.asmdef.meta
  Assets/EasyShortcutLockInspector-main/Editor/EasyShortCutLockInspector.cs
  Assets/EasyShortcutLockInspector-main/Editor/EasyShortCutLockInspector.cs.meta
  Assets/EasyShortcutLockInspector-main/README.md
  Assets/EasyShortcutLockInspector-main/README.md.meta
  Assets/EasyShortcutLockInspector-main/package.json
  Assets/EasyShortcutLockInspector-main/package.json.meta
Labels: General, System design

#161 Fixing coloreffects and updated combat
  Assets/Animations/Player/PlayerController.controller
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Player/ColorSystem/ColorEffects/BlueColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/BlueEffect.asset
  Assets/Player/ColorSystem/ColorEffects/BrownColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/BrownEffect.asset
  Assets/Player/ColorSystem/ColorEffects/ColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/GreenColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/GreenEffect.asset
  Assets/Player/ColorSystem/ColorEffects/OrangeColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/OrangeEffect.asset
  Assets/Player/ColorSystem/ColorEffects/PurpleColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/PurpleEffect.asset
  Assets/Player/ColorSystem/ColorEffects/RedColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/RedEffect.asset
  Assets/Player/ColorSystem/ColorEffects/YellowColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/YellowEffect.asset
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellImpact.cs
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Scenes/PlayerColorsCombatTest.unity
  Assets/TechArt/Particles/color/BlueParticles.prefab
Labels: Gameplay Design, System design

#194 Sleeping animations
  Assets/Animations/Big Cryss/BigCryssAnimator.controller
  Assets/Animations/Big Cryss/Big_Cryss_asleep.anim
  Assets/Animations/Big Cryss/Big_Cryss_asleep.anim.meta
  Assets/Animations/Big Cryss/Big_Cryss_fall_asleeps.anim
  Assets/Animations/Big Cryss/Big_Cryss_fall_asleeps.anim.meta
  Assets/Animations/Big Cryss/Big_Cryss_wake.anim
  Assets/Animations/Big Cryss/Big_Cryss_wake.anim.meta
  Assets/Animations/Big Cryss/big_cryss_asleep.png
  Assets/Animations/Big Cryss/big_cryss_asleep.png.meta
  Assets/Animations/Big Cryss/big_cryss_ded.png
  Assets/Animations/Big Cryss/big_cryss_falling_asleep.png
  Assets/Animations/Big Cryss/big_cryss_falling_asleep.png.meta
  Assets/Animations/Big Cryss/big_cryss_waking_up.png
  Assets/Animations/Big Cryss/big_cryss_waking_up.png.meta
  Assets/Animations/CrystalSword/Crystal_Sword_Controller.controller
  Assets/Animations/CrystalSword/Sleep-crystal-sword.anim
  Assets/Animations/CrystalSword/crystoffer_asleep.png
  Assets/Animations/CrystalSword/crystoffer_asleep.png.meta
  Assets/Animations/CrystalSword/crystoffer_falling_asleep.png
  Assets/Animations/CrystalSword/crystoffer_falling_asleep.png.meta
  Assets/Animations/CrystalSword/crystoffer_wake_up.png
  Assets/Animations/CrystalSword/crystoffer_wake_up.png.meta
  Assets/Enemies/Crystoffer_asleep.anim
  Assets/Enemies/Crystoffer_asleep.anim.meta
  Assets/Enemies/Crystoffer_fall_asleep.anim
  Assets/Enemies/Crystoffer_fall_asleep.anim.meta
  Assets/Enemies/Crystoffer_wake_up.anim
  Assets/Enemies/Crystoffer_wake_up.anim.meta
  Assets/Resources/Bottles/Materials/bottle 0.mat
  Assets/Resources/Bottles/Materials/bottle 1.mat
  Assets/Resources/Bottles/Materials/bottle 2.mat
  Assets/Resources/Bottles/Materials/bottle 3.mat
  Assets/TechArt/Shaders/Masks/big_cryss_asleep_mask.png
  Assets/TechArt/Shaders/Masks/big_cryss_asleep_mask.png.meta
  Assets/TechArt/Shaders/Masks/big_cryss_ded_mask.png
  Assets/TechArt/Shaders/Masks/big_cryss_falling_asleep_mask.png
  Assets/TechArt/Shaders/Masks/big_cryss_falling_asleep_mask.png.meta
  Assets/TechArt/Shaders/Masks/big_cryss_waking_up_mask.png
  Assets/TechArt/Shaders/Masks/big_cryss_waking_up_mask.png.meta
  Assets/TechArt/Shaders/Masks/crystoffer_asleep_mask.png
  Assets/TechArt/Shaders/Masks/crystoffer_asleep_mask.png.meta
  Assets/TechArt/Shaders/Masks/crystoffer_falling_asleep_mask.png
  Assets/TechArt/Shaders/Masks/crystoffer_falling_asleep_mask.png.meta
  Assets/TechArt/Shaders/Masks/crystoffer_wake_up_mask.png
  Assets/TechArt/Shaders/Masks/crystoffer_wake_up_mask.png.meta
Labels: Tech Art, Animation

#185 added healthBar to BigCriss
  Assets/Enemies/Big Cryss.prefab
Labels: UI Design

#196 Fixed enemies
  Assets/Animations/Big Cryss/BigCryssAnimator.controller
  Assets/Animations/CrystalCrawler/Crystal_Crawler_Animator.controller
  Assets/Animations/CrystalSword/Crystal_Sword_Controller.controller
  Assets/Enemies/Big Cryss.prefab
  Assets/Player/ColorSystem/GameColor.cs
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellImpact.cs
Labels: Gameplay Design, System design

#201 Added texture to allow non-bloom color to show
  Assets/Scenes/TechArtPlayground.unity
  Assets/TechArt/Shaders/Dynamic Color Materials/Blue.mat
  Assets/TechArt/Shaders/Dynamic Color Materials/Green.mat
  Assets/TechArt/Shaders/Dynamic Color Materials/Orange.mat
  Assets/TechArt/Shaders/Dynamic Color Materials/Purple.mat
  Assets/TechArt/Shaders/Dynamic Color Materials/Red.mat
  Assets/TechArt/Shaders/Dynamic Color Materials/Yellow.mat
  Assets/TechArt/Shaders/Glow.shadergraph
Labels: Tech Art

#208 Minimap
  Assets/Player/Player.prefab
  Assets/Resources/Minimap.meta
  Assets/Resources/Minimap/OutOfBounds.prefab
  Assets/Resources/Minimap/OutOfBounds.prefab.meta
  Assets/Resources/Minimap/RoomBasic.prefab
  Assets/Resources/Minimap/RoomBasic.prefab.meta
  Assets/Resources/Minimap/WallBasic.prefab
  Assets/Resources/Minimap/WallBasic.prefab.meta
  Assets/RoomGenerator2/LevelGenManager.cs
  Assets/RoomGenerator2/LevelGenerator.cs
  Assets/RoomGenerator2/Minimap.meta
  Assets/RoomGenerator2/Minimap/Minimap.cs
  Assets/RoomGenerator2/Minimap/Minimap.cs.meta
  Assets/TechArt/Minimap.meta
  Assets/TechArt/Minimap/MinimapOutput.renderTexture
  Assets/TechArt/Minimap/MinimapOutput.renderTexture.meta
  Assets/TechArt/Shaders/Minimap.mat
  Assets/TechArt/Shaders/Minimap.mat.meta
  Assets/TechArt/Shaders/Minimap.shadergraph
  Assets/TechArt/Shaders/Minimap.shadergraph.meta
  Assets/UI/PlayerUI/MapController.cs
  Assets/UI/PlayerUI/MapController.cs.meta
  Assets/UI/PlayerUI/PlayerUI.prefab
  ProjectSettings/TagManager.asset
Labels: Tech Art, UI Design

#210 Hp bar color tweaking
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/healthbarFrame.png
Labels: UI Design

#212 Added new MapBorder to map
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/map-border.png
  Assets/UI/PlayerUI/map-border.png.meta
Labels: Graphical design, UI Design

#248 Dynamic bottle updating
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Punch.prefab
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpell.cs
  Assets/UI/PlayerUI/ColorSlotController.cs
Labels: UI Design

#254 Decorating rooms
  Assets/Resources/Rooms/NormalRooms/Room 14.prefab
  Assets/Resources/Rooms/NormalRooms/Room 5.prefab
  Assets/TilesAndEnvironment/Cave Decorations.meta
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Floor Shroom 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Materials.meta
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 1.mat
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 1.mat.meta
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 2.mat
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 2.mat.meta
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 3.mat
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 3.mat.meta
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 4.mat
  Assets/TilesAndEnvironment/Cave Decorations/Materials/wall Shroom 4.mat.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roof Shroom 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 1.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 1.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 2.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 2.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 3.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Floor Shroom 3.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 1.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 1.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 2.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 2.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 3.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/Roof Shroom 3.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 1.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 1.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 2.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 2.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 3.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 3.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 4.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/wall Shroom 4.png.meta
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 4.prefab
  Assets/TilesAndEnvironment/Cave Decorations/wall Shroom 4.prefab.meta
  ProjectSettings/TagManager.asset
Labels: Gameplay Design

#251 Added movement root on map and updated movement root
  Assets/Player/PlayerMovement.cs
  Assets/UI/PlayerUI/MapController.cs
Labels: System design

#255 Added lightbox to objects behind map when it opens.
  Assets/UI/PlayerUI/MapController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
Labels: UI Design

#260 Dynamic bottle scaling
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Punch.prefab
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpell.cs
  Assets/UI/PlayerUI/Bottles/large_triangle_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/large_triangle_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/medium_circle_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_circle_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/medium_circle_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/medium_circle_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/medium_star_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_star_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/medium_star_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/medium_star_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/medium_triangle_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_triangle_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/medium_triangle_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/medium_triangle_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/small_circle_bottle.png
  Assets/UI/PlayerUI/Bottles/small_circle_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/small_circle_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/small_circle_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/small_star_bottle.png
  Assets/UI/PlayerUI/Bottles/small_star_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/small_star_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/small_star_bottle_mask.png.meta
  Assets/UI/PlayerUI/Bottles/small_triangle_bottle.png
  Assets/UI/PlayerUI/Bottles/small_triangle_bottle.png.meta
  Assets/UI/PlayerUI/Bottles/small_triangle_bottle_mask.png
  Assets/UI/PlayerUI/Bottles/small_triangle_bottle_mask.png.meta
  Assets/UI/PlayerUI/ColorSlotController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
Labels: UI Design

#264 Fixed bottles
  Assets/TechArt/Shaders/Bottle/Bottle.shadergraph
  Assets/TechArt/Shaders/Bottle/paintWave.png
  Assets/UI/PlayerUI/ColorSlotController.cs
Labels: Tech Art, UI Design

#265 Updated rainbow effect
  Assets/Player/ColorSystem/ColorEffects/BrownColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/BrownEffect.asset
  Assets/UI/PlayerUI/Bottles/large_triangle_bottle_mask.png.meta
Labels: Gameplay Design

#275 Uploaded animation sprite sheets for crystal quake
  Assets/.DS_Store
  Assets/Animations/.DS_Store
  Assets/Animations/CrystalQuake.meta
  Assets/Animations/CrystalQuake/Quake_controller.controller
  Assets/Animations/CrystalQuake/Quake_controller.controller.meta
  Assets/Animations/CrystalQuake/crystalQuake_Attack.png
  Assets/Animations/CrystalQuake/crystalQuake_Attack.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Death-Sheet.png
  Assets/Animations/CrystalQuake/crystalQuake_Death-Sheet.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Idle-Sheet.png
  Assets/Animations/CrystalQuake/crystalQuake_Idle-Sheet.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-Asleep.png
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-Asleep.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-FallAsleept.png
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-FallAsleept.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-WakeUp.png
  Assets/Animations/CrystalQuake/crystalQuake_Sleep-WakeUp.png.meta
  Assets/Animations/CrystalQuake/crystalQuake_Walk-Sheet.png
  Assets/Animations/CrystalQuake/crystalQuake_Walk-Sheet.png.meta
Labels: Animation

#288 Fixing spell, attack, item and movement bugs and fixes
  Assets/Enemies/Scripts/Enemy.cs
  Assets/Player/Items/Item.cs
  Assets/Player/Items/ItemEffects/ItemEffect.cs
  Assets/Player/Items/ItemInventory.cs
  Assets/Player/Items/ItemManager.cs
  Assets/Player/Items/ItemPickup.cs
  Assets/Player/Player.prefab
  Assets/Player/PlayerMovement.cs
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellImpact.cs
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Resources/Bottles/Materials/bottle 0.mat
  Assets/Resources/Bottles/Materials/bottle 1.mat
Labels: Gameplay Design, System design
