Repository Message-Photon-Studios/Rock-Bottom, pull requests merged in 2023-05, with the labels that each got.

#297 made text change color if active or not
  Assets/Scenes/MainMenu.unity
  Assets/UI/MainMenuUI/Alkatra.asset
  Assets/UI/MainMenuUI/IndicatorController.cs
  Assets/UI/MainMenuUI/IndicatorController.cs.meta
  Assets/UI/MainMenuUI/MainMenuController.cs
  Assets/UI/MainMenuUI/MainMenuController.cs.meta
Labels: UI Design

#314 Show coins
  Assets/Player/Items/ItemPickup.cs
  Assets/UI/PlayerUI/CoinController.cs
  Assets/UI/PlayerUI/CoinController.cs.meta
  Assets/UI/PlayerUI/CoinFrame.png
  Assets/UI/PlayerUI/CoinFrame.png.meta
  Assets/UI/PlayerUI/CoinFrameMask.png
  Assets/UI/PlayerUI/CoinFrameMask.png.meta
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/big-coin.png
  Assets/UI/PlayerUI/big-coin.png.meta
  Assets/UI/PlayerUI/small-coin.png
  Assets/UI/PlayerUI/small-coin.png.meta
Labels: UI Design

#326 Fixed error that made enemies spawned by spawners not be culled correctly
  Assets/RoomGenerator2/LevelGenerator.cs
Labels: System design

#327 Dmg numbers
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Scripts/DmgNumber.cs
  Assets/Enemies/Scripts/DmgNumber.cs.meta
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SpawnAttackObjs/Bombarder Projectile.prefab
  Assets/Player/ColorSpells/SubSpells/ColorBombExplosion.prefab
  Assets/Resources/Bottles/Materials/bottle 1.mat
  Assets/Resources/DmgNumbers.meta
  Assets/Resources/DmgNumbers/DmgNumber.prefab
  Assets/Resources/DmgNumbers/DmgNumber.prefab.meta
Labels: Tech Art, System design

#347 Poison bug fix
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SpawnAttackObjs/Bombarder Projectile.prefab
  Assets/Player/ColorSystem/ColorEffects/BrownColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/OrangeEffect.asset
  Assets/Player/ColorSystem/ColorEffects/YellowColorEffect.cs
  Assets/Player/ColorSystem/GameColor.cs
  Assets/Resources/Bottles/Materials/bottle 1.mat
Labels: System design

#325 Stats/inventory view
  Assets/Player/Items/ItemInventory.cs
  Assets/UI/MainMenuUI/32PT Abaddon Bold.asset
  Assets/UI/MainMenuUI/32PT Abaddon Bold.asset.meta
  Assets/UI/MainMenuUI/64PT Abaddon Bold.asset
  Assets/UI/MainMenuUI/64PT Abaddon Bold.asset.meta
  Assets/UI/MainMenuUI/Abaddon Bold.ttf
  Assets/UI/MainMenuUI/Abaddon Bold.ttf.meta
  Assets/UI/MainMenuUI/Abaddon Light.ttf
  Assets/UI/MainMenuUI/Abaddon Light.ttf.meta
  Assets/UI/PlayerUI/Divider.png
  Assets/UI/PlayerUI/Divider.png.meta
  Assets/UI/PlayerUI/DividerOutline.png
  Assets/UI/PlayerUI/DividerOutline.png.meta
  Assets/UI/PlayerUI/LightboxController.cs
  Assets/UI/PlayerUI/LightboxController.cs.meta
  Assets/UI/PlayerUI/MapController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/inventory-border-mask.png
  Assets/UI/PlayerUI/inventory-border-mask.png.meta
  Assets/UI/PlayerUI/inventory-border.png
  Assets/UI/PlayerUI/inventory-border.png.meta
  Assets/UI/PlayerUI/inventory.meta
  Assets/UI/PlayerUI/inventory/Item.prefab
  Assets/UI/PlayerUI/inventory/Item.prefab.meta
  Assets/UI/PlayerUI/inventory/ItemController.cs
  Assets/UI/PlayerUI/inventory/ItemController.cs.meta
  Assets/UI/PlayerUI/inventory/NotifyInventory.cs
  Assets/UI/PlayerUI/inventory/NotifyInventory.cs.meta
  Assets/UI/PlayerUI/inventory/SelectedInventoryItem.cs
  Assets/UI/PlayerUI/inventory/SelectedInventoryItem.cs.meta
  Assets/UI/PlayerUI/inventory/StatsController.cs
  Assets/UI/PlayerUI/inventory/StatsController.cs.meta
  Assets/UI/PlayerUI/inventory/big-coin.png
  Assets/UI/PlayerUI/inventory/big-coin.png.meta
  Assets/UI/PlayerUI/inventory/blue-icon.png
  Assets/UI/PlayerUI/inventory/blue-icon.png.meta
  Assets/UI/PlayerUI/inventory/green-icon.png
  Assets/UI/PlayerUI/inventory/green-icon.png.meta
  Assets/UI/PlayerUI/inventory/orange-icon.png
  Assets/UI/PlayerUI/inventory/orange-icon.png.meta
  Assets/UI/PlayerUI/inventory/purple-icon.png
  Assets/UI/PlayerUI/inventory/purple-icon.png.meta
  Assets/UI/PlayerUI/inventory/red-icon.png
  Assets/UI/PlayerUI/inventory/red-icon.png.meta
  Assets/UI/PlayerUI/inventory/white-icon.png
  Assets/UI/PlayerUI/inventory/white-icon.png.meta
  Assets/UI/PlayerUI/inventory/yellow-icon.png
  Assets/UI/PlayerUI/inventory/yellow-icon.png.meta
Labels: UI Design

#352 Power indicator
  Assets/Player/ColorSystem/GameColor.cs
  Assets/Player/ColorSystem/GameColor/Blue.asset
  Assets/Player/ColorSystem/GameColor/Brown.asset
  Assets/Player/ColorSystem/GameColor/Green.asset
  Assets/Player/ColorSystem/GameColor/Orange.asset
  Assets/Player/ColorSystem/GameColor/Purple.asset
  Assets/Player/ColorSystem/GameColor/Red.asset
  Assets/Player/ColorSystem/GameColor/Yellow.asset
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpell.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/PrIndicationController.cs
  Assets/UI/PlayerUI/PrIndicationController.cs.meta
Labels: UI Design

#350 Added sirfly to rooms
  Assets/Enemies/Spikey.prefab
  Assets/Resources/Bottles/Materials/bottle 0.mat
  Assets/Resources/Bottles/Materials/bottle 1.mat
  Assets/Resources/Bottles/Materials/bottle 2.mat
  Assets/Resources/Bottles/Materials/bottle 3.mat
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 11.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 13.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 15.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 2.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 20.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 21.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 7.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 8.prefab
Labels: Gameplay Design

#358 Fixing buggs
  Assets/Animations/Big Cryss/BigCryssAnimator.controller
  Assets/Animations/CrystalSword/Crystal_Sword_Controller.controller
  Assets/Animations/Player/Sylvia-damaged.anim
  Assets/Animations/SirFly/wake up.anim
  Assets/Animations/Spikey/Spikey_wake_up.anim
  Assets/Enemies/Scripts/CrystalCrawler.cs
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SirFly.prefab
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Punch.prefab
  Assets/Player/Items/ItemPickup.prefab
  Assets/Player/Items/SpellPickup.prefab
  Assets/Player/Player.prefab
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpellImpact.cs
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Scenes/PlayerColorsCombatTest.unity
  Assets/sounds/enemies/EnemySounds.prefab
  Assets/sounds/environment/environmentSounds.prefab
Labels: System design

#360 Improve spell particles
  Assets/Resources/Bottles/Materials/bottle 1.mat
  Assets/TechArt/Particles/SpellExplosion.prefab
  Assets/TechArt/Particles/SpellImpact.prefab
Labels: Graphical design, Tech Art

#362 Added color stats as selectable objects
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/inventory/ItemController.cs
  Assets/UI/PlayerUI/inventory/SelectedColor.cs
  Assets/UI/PlayerUI/inventory/SelectedColor.cs.meta
Labels: UI Design

#363 Healthbar improvements
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SirFly.prefab
  Assets/Enemies/SirFlyL.prefab
  Assets/Enemies/SirFlyR.prefab
  Assets/Enemies/SirFlyU.prefab
  Assets/Enemies/Spikey.prefab
  Assets/Resources/Bottles/Materials/bottle 0.mat
  Assets/Scenes/TechArtPlayground.unity
  Assets/TechArt/Shaders/Glow.shadergraph
  Assets/UI/EnemyUI/EffectIconController.cs
  Assets/UI/EnemyUI/EffectIconController.cs.meta
  Assets/UI/EnemyUI/EnemyHp.prefab
  Assets/UI/EnemyUI/EnemyHpController.cs
  Assets/UI/EnemyUI/HpFrame.png
  Assets/UI/EnemyUI/HpFrame.png.meta
Labels: UI Design

#369 Balancing
  Assets/Animations/CrystalBombarder/Crystal_Bombarder.controller
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/SirFly.prefab
  Assets/Enemies/SirFlyL.prefab
  Assets/Enemies/SirFlyR.prefab
  Assets/Enemies/SirFlyU.prefab
  Assets/Enemies/SpawnAttackObjs/Bombarder Projectile.prefab
  Assets/Enemies/SpawnAttackObjs/SirFly Projectile.prefab
  Assets/Enemies/Spikey.prefab
  Assets/Player/ColorSpells/Color Bloom.prefab
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Punch.prefab
  Assets/Player/ColorSystem/ColorEffects/BrownEffect.asset
  Assets/Player/ColorSystem/ColorEffects/GreenEffect.asset
  Assets/Player/ColorSystem/GameColor/Blue.asset
  Assets/Player/ColorSystem/GameColor/Green.asset
  Assets/Player/ColorSystem/GameColor/Orange.asset
  Assets/Player/ColorSystem/GameColor/Purple.asset
  Assets/Player/ColorSystem/GameColor/Rainbow.asset
  Assets/Player/ColorSystem/GameColor/Rainbow.asset.meta
  Assets/Player/ColorSystem/GameColor/Red.asset
  Assets/Player/ColorSystem/GameColor/Yellow.asset
  Assets/Player/Items/Items/Blue Rimfrost.asset
  Assets/Player/Items/Items/Crystal Hearth.asset
  Assets/Player/Items/Items/Green Death.asset
  Assets/Player/Items/Items/Orange Flames.asset
  Assets/Player/Items/Items/Purple Night.asset
  Assets/Player/Items/Items/Rainbow Charm.asset
  Assets/Player/Items/Items/Red Leaches.asset
  Assets/Player/Items/Items/Yellow Thunder.asset
  Assets/TechArt/Shaders/BrownGlow.shadergraph
  Assets/TechArt/Shaders/Dynamic Color Materials/Brown.mat
Labels: Gameplay Design

#371 Damage numbers are now ints
  Assets/Enemies/Scripts/DmgNumber.cs
  Assets/UI/EnemyUI/EnemyHp.prefab
Labels: Tech Art, UI Design

#372 Balanced rooms
  Assets/Resources/Bottles/Materials/bottle 0.mat
  Assets/Resources/Bottles/Materials/bottle 3.mat
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 1.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 13.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 14.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 15.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 16.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 17.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 20.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 21.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 22.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 3.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 4.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 5.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 6.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 7.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 8.prefab
Labels: Gameplay Design

#377 Samuel crunch
  Assets/UI/PlayerUI/ButtonPrompts/RT.png
  Assets/UI/PlayerUI/ButtonPrompts/backpack.png
  Assets/UI/PlayerUI/ButtonPrompts/backpack.png.meta
  Assets/UI/PlayerUI/ButtonPrompts/m.png
  Assets/UI/PlayerUI/ButtonPrompts/map.png
  Assets/UI/PlayerUI/ButtonPrompts/showLoadout.png
  Assets/UI/PlayerUI/ButtonPrompts/showLoadout.png.meta
  Assets/UI/PlayerUI/ButtonPrompts/tab.png
  Assets/UI/PlayerUI/ButtonPrompts/tab.png.meta
  Assets/UI/PlayerUI/ButtonPrompts/zoom.png
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/inventory/ItemController.cs
Labels: UI Design

#379 Updated interaction with items/bottles
  Assets/Player/Items/ItemPickup.prefab
  Assets/Player/Items/SpellPickup.prefab
  Assets/UI/PlayerUI/ButtonPrompts/F.png
  Assets/UI/PlayerUI/ButtonPrompts/F.png.meta
  Assets/UI/PlayerUI/ButtonPrompts/controllerB.png
  Assets/UI/PlayerUI/ButtonPrompts/controllerB.png.meta
Labels: UI Design

#383 Bottles in inventory
  Assets/Player/Items/SpellPickup.prefab
  Assets/UI/PlayerUI/ColorSlotController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/UI/PlayerUI/inventory/Bottle.prefab
  Assets/UI/PlayerUI/inventory/Bottle.prefab.meta
  Assets/UI/PlayerUI/inventory/ItemController.cs
  Assets/UI/PlayerUI/inventory/SelectedBottle.cs
  Assets/UI/PlayerUI/inventory/SelectedBottle.cs.meta
Labels: UI Design

#381 Added title to main menu and small update
  Assets/Scenes/MainMenu.unity
  Assets/UI/MainMenuUI/IndicatorController.cs
  Assets/UI/MainMenuUI/MainMenuController.cs
Labels: UI Design

#374 SirFly Balancing
  Assets/Animations/SirFly/hold.anim
  Assets/Enemies/SirFly.prefab
  Assets/Enemies/SirFlyL.prefab
  Assets/Enemies/SirFlyR.prefab
  Assets/Enemies/SirFlyU.prefab
  Assets/Enemies/SpawnAttackObjs/SirFly Projectile.prefab
  Assets/Resources/Bottles/Materials/body/bottle 0.mat
  Assets/Resources/Bottles/Materials/body/bottle 1.mat
  Assets/Resources/Bottles/Materials/body/bottle 2.mat
  Assets/Resources/Bottles/Materials/body/bottle 3.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 0.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 1.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 2.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 3.mat
  Assets/Scenes/PlayerColorsCombatTest.unity
Labels: Gameplay Design

#403 Fixes
  Assets/Resources/Bottles/Materials/body/bottle 0.mat
  Assets/Resources/Bottles/Materials/body/bottle 1.mat
  Assets/Resources/Bottles/Materials/body/bottle 2.mat
  Assets/Resources/Bottles/Materials/body/bottle 3.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 1.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 2.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 3.mat
  Assets/Resources/Rooms/CrystalCaves/ClosingRooms/Room 14.prefab
  Assets/Resources/Rooms/CrystalCaves/ClosingRooms/Room 3.prefab
  Assets/Resources/Rooms/CrystalCaves/ClosingRooms/Room 4.prefab
  Assets/Resources/Rooms/CrystalCaves/ClosingRooms/Room 5.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 1.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 11.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 12.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 13.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 14.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 15.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 16.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 17.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 19.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 2.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 20.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 21.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 22.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 3.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 4.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 5.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 6.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 7.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 8.prefab
  Assets/Resources/Rooms/CrystalCaves/endRooms/endRoom.prefab
  ProjectSettings/ProjectSettings.asset
Labels: General

#406 Numbers now say "immune" and have their own type
  Assets/Enemies/Scripts/DmgNumber.cs
  Assets/Resources/DmgNumbers/DmgNumber.prefab
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Outline.mat
Labels: System design

#440 Enemy fixes
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Dummy.prefab
  Assets/Enemies/EnemyBehaviours/AirPatroll.cs
  Assets/Enemies/EnemyBehaviours/CheckGrounded.cs
  Assets/Enemies/EnemyBehaviours/CheckWall.cs
  Assets/Enemies/Scripts/CrystalCrawler.cs
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/Scripts/Spikey.cs
  Assets/Enemies/SpawnAttackObjs/Bombarder Projectile.prefab
  Assets/Enemies/Spikey.prefab
  Assets/GameManager/LevelEndPoint.prefab
  Assets/Player/Items/SpellPickup.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 13.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 15.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 16.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 17.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 18.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 19.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 21.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 22.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 3.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 5.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 6.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 8.prefab
  Assets/Scenes/PlayerColorsCombatTest.unity
Labels: Gameplay Design, System design

#446 Fixing coloreffects
  Assets/Animations/CrystalBombarder/Bombarder_projectile.controller
  Assets/Animations/Player/Player-attack-hand.anim
  Assets/Animations/Player/Player-default-attack.anim
  Assets/Animations/Player/PlayerController.controller
  Assets/Animations/Player/Sylvia-attack-raised.anim
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Player/ColorSystem/ColorEffects/GreenColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/PurpleColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/RainbowEffect.asset
  Assets/Player/ColorSystem/ColorEffects/RainbowEffect.asset.meta
  Assets/Player/ColorSystem/ColorEffects/YellowEffect.asset
  Assets/Player/ColorSystem/ColorInventory.cs
  Assets/Player/ColorSystem/GameColor/Blue.asset
  Assets/Player/ColorSystem/GameColor/Green.asset
  Assets/Player/ColorSystem/GameColor/Orange.asset
  Assets/Player/ColorSystem/GameColor/Purple.asset
  Assets/Player/ColorSystem/GameColor/Rainbow.asset
  Assets/Player/ColorSystem/GameColor/Red.asset
  Assets/Player/ColorSystem/GameColor/Yellow.asset
  Assets/Player/PlayerStats.cs
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  Assets/Resources/Bottles/Materials/body/bottle 0.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 0.mat
Labels: Gameplay Design, System design

#448 Sylvia healthbar
  Assets/UI/PlayerUI/PlayerHpController.cs
  Assets/UI/PlayerUI/PlayerUI.prefab
Labels: UI Design

#470 Improved health initialization and fixed numbers going negative
  Assets/UI/PlayerUI/PlayerHpController.cs
Labels: UI Design

#469 Added Map Icons
  Assets/Player/Items/ItemPickup.prefab
  Assets/Player/Items/SpellPickup.prefab
  Assets/Player/Player.prefab
  Assets/Resources/Minimap/icons.meta
  Assets/Resources/Minimap/icons/bottle_map_icon.png
  Assets/Resources/Minimap/icons/bottle_map_icon.png.meta
  Assets/Resources/Minimap/icons/bottle_map_icon.prefab
  Assets/Resources/Minimap/icons/bottle_map_icon.prefab.meta
  Assets/Resources/Minimap/icons/item_map_icon.png
  Assets/Resources/Minimap/icons/item_map_icon.png.meta
  Assets/Resources/Minimap/icons/item_map_icon.prefab
  Assets/Resources/Minimap/icons/item_map_icon.prefab.meta
  Assets/Resources/Minimap/icons/sylvia_map_icon.png
  Assets/Resources/Minimap/icons/sylvia_map_icon.png.meta
  Assets/Resources/Minimap/icons/sylvia_map_icon.prefab
  Assets/Resources/Minimap/icons/sylvia_map_icon.prefab.meta
  Assets/RoomGenerator2/LevelGenerator.cs
  Assets/UI/PlayerUI/Bottles/large_bloom_bottle.png
  Assets/UI/PlayerUI/Bottles/large_circle_bottle.png
  Assets/UI/PlayerUI/Bottles/large_claw_bottle.png
  Assets/UI/PlayerUI/Bottles/large_fist_bottle.png
  Assets/UI/PlayerUI/Bottles/large_star_bottle.png
  Assets/UI/PlayerUI/Bottles/large_triangle_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_bloom_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_circle_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_claw_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_fist_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_star_bottle.png
  Assets/UI/PlayerUI/Bottles/medium_triangle_bottle.png
  Assets/UI/PlayerUI/Bottles/small_bloom_bottle.png
  Assets/UI/PlayerUI/Bottles/small_circle_bottle.png
  Assets/UI/PlayerUI/Bottles/small_claw_bottle.png
  Assets/UI/PlayerUI/Bottles/small_fist_bottle.png
  Assets/UI/PlayerUI/Bottles/small_star_bottle.png
  Assets/UI/PlayerUI/Bottles/small_triangle_bottle.png
Labels: Graphical design, Tech Art, UI Design

#471 Root and shroom decorations
  Assets/Resources/Bottles/Materials/body/bottle 0.mat
  Assets/Resources/Bottles/Materials/body/bottle 1.mat
  Assets/Resources/Bottles/Materials/body/bottle 3.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 1.mat
  Assets/Resources/Bottles/Materials/cap/bottleCap 3.mat
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 12.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 13.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 22.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 3.prefab
  Assets/Resources/Rooms/CrystalCaves/NormalRooms/Room 5.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/carrot root 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/carrot root 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/carrot root 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/carrot root 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/medium root 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/small root 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/thick root 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 1.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 1.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 2.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 2.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 3.prefab
  Assets/TilesAndEnvironment/Cave Decorations/Roots/wall root 3.prefab.meta
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/roots.png
  Assets/TilesAndEnvironment/Cave Decorations/Sprites/roots.png.meta
Labels: Graphical design

#477 Fixed editor level generator and added room spawn limit
  Assets/GameManager/GameManager.cs
  Assets/RoomGenerator2/Editor/LevelGenManagerEditor.cs
  Assets/RoomGenerator2/LevelGenManager.cs
  Assets/RoomGenerator2/LevelGenerator.cs
  Assets/RoomGenerator2/RoomPreset/CustomRoom.cs
Labels: System design

#475 Balancing after test
  Assets/Animations/Player/PlayerController.controller
  Assets/AutoRenderLayerEditor.cs
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Dummy.prefab
  Assets/Enemies/EnemyBehaviours/CheckWall.cs
  Assets/Enemies/Scripts/CrystalCrawler.cs
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SirFly.prefab
  Assets/Enemies/SirFlyL.prefab
  Assets/Enemies/SirFlyR.prefab
  Assets/Enemies/SirFlyU.prefab
  Assets/Enemies/Spikey.prefab
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Claws.prefab
  Assets/Player/ColorSystem/ColorEffects/BrownColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/GreenColorEffect.cs
  Assets/Player/ColorSystem/ColorEffects/GreenEffect.asset
  Assets/Player/ColorSystem/ColorEffects/PurpleEffect.asset
  Assets/Player/ColorSystem/ColorEffects/RainbowEffect.asset
  Assets/Player/ColorSystem/ColorInventory.cs
  Assets/Player/ColorSystem/GameColor.cs
  Assets/Player/ColorSystem/GameColor/Green.asset
  Assets/Player/ColorSystem/GameColor/Purple.asset
  Assets/Player/ColorSystem/GameColor/Rainbow.asset
  Assets/Player/Player.prefab
  Assets/Player/SpellsSystem/PlayerCombatSystem.cs
  ProjectSettings/Physics2DSettings.asset
Labels: Gameplay Design

#490 Added coin drops!!
  Assets/Enemies/Big Cryss.prefab
  Assets/Enemies/Coins.meta
  Assets/Enemies/Coins/CoinItem.cs
  Assets/Enemies/Coins/CoinItem.cs.meta
  Assets/Enemies/Coins/astral_SPARK-assets.meta
  Assets/Enemies/Coins/astral_SPARK-assets/astral_SPARK.png
  Assets/Enemies/Coins/astral_SPARK-assets/astral_SPARK.png.meta
  Assets/Enemies/Coins/astral_SPARK.png
  Assets/Enemies/Coins/astral_SPARK.png.meta
  Assets/Enemies/Coins/astral_SPARK_0.controller
  Assets/Enemies/Coins/astral_SPARK_0.controller.meta
  Assets/Enemies/Coins/coinSparkle.anim
  Assets/Enemies/Coins/coinSparkle.anim.meta
  Assets/Enemies/Crystal Bombarder.prefab
  Assets/Enemies/Crystal Crawler.prefab
  Assets/Enemies/Crystoffer.prefab
  Assets/Enemies/Scripts/EnemyStats.cs
  Assets/Enemies/SirFly.prefab
  Assets/Enemies/SirFlyL.prefab
  Assets/Enemies/SirFlyR.prefab
  Assets/Enemies/SirFlyU.prefab
  Assets/Enemies/Spikey.prefab
  Assets/Player/CoinPickupEffect.cs
  Assets/Player/CoinPickupEffect.cs.meta
  Assets/Player/Items/ItemInventory.cs
  Assets/Player/Player.prefab
  Assets/Player/PlayerSprite/CoinSparkPlayer.anim
  Assets/Player/PlayerSprite/CoinSparkPlayer.anim.meta
  Assets/Player/PlayerSprite/astral_SPARK.png
  Assets/Player/PlayerSprite/astral_SPARK.png.meta
  Assets/Player/PlayerSprite/coinPickup.controller
  Assets/Player/PlayerSprite/coinPickup.controller.meta
  Assets/Player/coinPickup.prefab
  Assets/Player/coinPickup.prefab.meta
  Assets/Resources/BreathingBloom.meta
  Assets/Resources/BreathingBloom/BreathBlue.mat
  Assets/Resources/BreathingBloom/BreathBlue.mat.meta
  Assets/Resources/BreathingBloom/BreathGreen.mat
  Assets/Resources/BreathingBloom/BreathGreen.mat.meta
  Assets/Resources/BreathingBloom/BreathOrange.mat
  Assets/Resources/BreathingBloom/BreathOrange.mat.meta
  Assets/Resources/BreathingBloom/BreathPurple.mat
  Assets/Resources/BreathingBloom/BreathPurple.mat.meta
  Assets/Resources/BreathingBloom/BreathRed.mat
  Assets/Resources/BreathingBloom/BreathRed.mat.meta
  Assets/Resources/BreathingBloom/BreathYellow.mat
  Assets/Resources/BreathingBloom/BreathYellow.mat.meta
  Assets/Resources/Coins.meta
  Assets/Resources/Coins/coin1.prefab
  Assets/Resources/Coins/coin1.prefab.meta
  Assets/Resources/Coins/coin5.prefab
  Assets/Resources/Coins/coin5.prefab.meta
  Assets/UI/PlayerUI/PlayerUI.prefab
  Assets/sounds/player/raw/coins27-36030_01.wav
  Assets/sounds/player/raw/coins27-36030_01.wav.meta
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: Graphical design, Tech Art, System design

#492 Added some nice touches to coins
  Assets/Enemies/Coins/CoinItem.cs
  Assets/Player/coinPickup.prefab
Labels: Tech Art

#493 Update PlayerUI.prefab
  Assets/UI/PlayerUI/PlayerUI.prefab
Labels: UI Design

#495 Fixed bomb spell and claws spell
  Assets/Player/ColorSpells/Color Bloom.prefab
  Assets/Player/ColorSpells/Color Bolt.prefab
  Assets/Player/ColorSpells/Color Bomb.prefab
  Assets/Player/ColorSpells/Color Claws.prefab
  Assets/Player/ColorSpells/Color Punch.prefab
  Assets/Player/ColorSpells/SubSpells/ColorBombExplosion.prefab
  Assets/Player/ColorSpells/SubSpells/ColorTrapActive.prefab
  Assets/Player/SpellsSystem/ColorSpellScripts/ColorSpell.cs
Labels: Gameplay Design, System design
